// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	bytes "bytes"
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ElasticDB is an autogenerated mock type for the ElasticDB type
type ElasticDB struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id, indexname
func (_m *ElasticDB) Delete(ctx *context.Context, id string, indexname string) error {
	ret := _m.Called(ctx, id, indexname)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.Context, string, string) error); ok {
		r0 = rf(ctx, id, indexname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Index provides a mock function with given fields: ctx, buf, indexname, id
func (_m *ElasticDB) Index(ctx *context.Context, buf bytes.Buffer, indexname string, id string) error {
	ret := _m.Called(ctx, buf, indexname, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.Context, bytes.Buffer, string, string) error); ok {
		r0 = rf(ctx, buf, indexname, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, buf, indexname
func (_m *ElasticDB) Search(ctx *context.Context, buf bytes.Buffer, indexname string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, buf, indexname)

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(*context.Context, bytes.Buffer, string) (io.ReadCloser, error)); ok {
		return rf(ctx, buf, indexname)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, bytes.Buffer, string) io.ReadCloser); ok {
		r0 = rf(ctx, buf, indexname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context, bytes.Buffer, string) error); ok {
		r1 = rf(ctx, buf, indexname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewElasticDB creates a new instance of ElasticDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElasticDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElasticDB {
	mock := &ElasticDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
