// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/ismailOzone/GO-BOOKS-PROJECT/pkg/books/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Createbook provides a mock function with given fields: c, book
func (_m *Service) Createbook(c *context.Context, book *models.Book) error {
	ret := _m.Called(c, book)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.Context, *models.Book) error); ok {
		r0 = rf(c, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deletebook provides a mock function with given fields: c, id
func (_m *Service) Deletebook(c *context.Context, id string) error {
	ret := _m.Called(c, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.Context, string) error); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetbookByID provides a mock function with given fields: c, id
func (_m *Service) GetbookByID(c *context.Context, id string) (*models.Book, error) {
	ret := _m.Called(c, id)

	var r0 *models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(*context.Context, string) (*models.Book, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(*context.Context, string) *models.Book); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Getbooks provides a mock function with given fields: c
func (_m *Service) Getbooks(c *context.Context) ([]*models.Book, error) {
	ret := _m.Called(c)

	var r0 []*models.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(*context.Context) ([]*models.Book, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*context.Context) []*models.Book); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(*context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Updatebook provides a mock function with given fields: c, book
func (_m *Service) Updatebook(c *context.Context, book *models.Book) error {
	ret := _m.Called(c, book)

	var r0 error
	if rf, ok := ret.Get(0).(func(*context.Context, *models.Book) error); ok {
		r0 = rf(c, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
